### ISSUE TITLE
Borrow without borrower name

### ISSUE THREAD

**Issue by stanlylau** [rvignesh89/tslib#3]

**Comment by rvignesh89** [comment]
Thinking of implementing a button to just change the status to borrow for now, what do you think @stanlylau ?

**Comment by stanlylau** [comment]
Sounds great! Do you want to know who is borrowing?

**Comment by rvignesh89** [comment]
At the moment maybe not. Once I'm able to change the status I'll add in the details of who is borrowing.

**Comment by stanlylau** [comment]
Should we do a bit more up-front design of how the model(s) could evolve?
